#cloud-config
# vim: syntax=yaml

# Set password module works for default account - 'ubuntu' in case of Ubuntu Cloud Images
# While it is a nice to set a password in demo systems, this is a potential security threat, DO NOT DO THIS in production systems
password: $6$rounds=4096$9aqHXgHRwyFPNCz3$1IR5TIIleTc3S.7UbF8MCmeDXThhz2fNr7YFerbW5ybuvzxlQezqiDh2lGFrV3VXMuOPxeC6.Q8ZJ1jOv97fE1
chpasswd:
    expire: false

packages:
  - mariadb-server
  - rpl

write_files:
  - content: |
         hostname=$(curl -ss http://169.254.169.254/2009-04-04/meta-data/hostname | cut -f 1 -d '.')
         localipv4=$(curl -ss http://169.254.169.254/2009-04-04/meta-data/local-ipv4)
         cat <<-EOF | mysql
         create database wordpressdb;
         grant all privileges on wordpressdb.* to 'wordpressuser'@'%' identified by 'openstack';
         grant all privileges on wordpressdb.* to 'wordpressuser'@'localhost' identified by 'openstack';
         flush privileges;
         EOF
         rpl 127.0.0.1 $localipv4 /etc/mysql/mariadb.conf.d/50-server.cnf
         service mysql restart
         echo "$localipv4 $hostname" >> /etc/hosts
    owner: root:root
    path: /tmp/start_me_up.sh
    permissions: '0700'

runcmd:
  - sh /tmp/start_me_up.sh
